In [24]:
import pandas as pd
import numpy as np
train_data = pd.read_csv("train_tit.csv", delimiter = ',')

In [7]:
print(train_data)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False
...          ...        ...       ...       ...            ...   ...    ...
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines
...           ...        ...           ...     ...     ...                ...
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre

      Transported
0           False
1            True
2           False
3           False
4            True
...           ...
8688        False
8689        False
8690         True
8691        False
8692         True

[8693 rows x 14 columns]

In [35]:
X = pd.DataFrame(train_data.drop(['PassengerId', 'Name' , 'VRDeck', 'Spa' , 'ShoppingMall' , 'FoodCourt', 'RoomService','VIP' , 'Age' , 'Destination' , 'HomePlanet','Transported'], axis=1))

In [36]:
X

     CryoSleep     Cabin
0        False     B/0/P
1        False     F/0/S
2        False     A/0/S
3        False     A/0/S
4        False     F/1/S
...        ...       ...
8688     False    A/98/P
8689      True  G/1499/S
8690     False  G/1500/S
8691     False   E/608/S
8692     False   E/608/S

[8693 rows x 2 columns]

In [14]:
y = pd.DataFrame(train_data['Transported']).values.ravel()

In [22]:
y

array([False,  True, False, ...,  True, False,  True])

In [23]:
type(y)

numpy.ndarray

In [31]:
y = y.astype('int')

In [118]:
y = pd.DataFrame(y)

      Transported
0               0
1               1
2               0
3               0
4               1
...           ...
8688            0
8689            0
8690            1
8691            0
8692            1

[8693 rows x 1 columns]

In [119]:
Cab = X['Cabin']

In [120]:
Cab

0          B/0/P
1          F/0/S
2          A/0/S
3          A/0/S
4          F/1/S
          ...
8688      A/98/P
8689    G/1499/S
8690    G/1500/S
8691     E/608/S
8692     E/608/S
Name: Cabin, Length: 8693, dtype: object

In [121]:
sectors = []
for i in range(len(Cab)):
    if ord(str(Cab[i])[0]) == 110:
        sectors.append(78-65-6)
    else:
        sectors.append(ord(str(Cab[i])[0])-65)
sectors

[1,
 5,
 0,
 0,
 5,
 5,
 5,
 6,
 5,
 1,
 1,
 1,
 5,
 6,
 5,
 7,
 5,
 5,
 5,
 6,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 2,
 5,
 2,
 5,
 6,
 5,
 5,
 5,
 3,
 3,
 5,
 5,
 6,
 6,
 1,
 6,
 6,
 6,
 5,
 5,
 4,
 4,
 6,
 5,
 0,
 0,
 0,
 6,
 5,
 5,
 5,
 4,
 6,
 6,
 6,
 5,
 4,
 5,
 5,
 5,
 5,
 3,
 2,
 5,
 5,
 2,
 6,
 5,
 5,
 5,
 6,
 2,
 5,
 4,
 6,
 6,
 5,
 6,
 6,
 6,
 0,
 6,
 6,
 5,
 6,
 7,
 5,
 5,
 6,
 6,
 5,
 3,
 6,
 6,
 6,
 7,
 1,
 1,
 1,
 4,
 1,
 5,
 6,
 5,
 3,
 0,
 0,
 5,
 6,
 5,
 5,
 4,
 3,
 4,
 6,
 5,
 3,
 6,
 6,
 6,
 4,
 2,
 6,
 5,
 5,
 5,
 6,
 6,
 5,
 6,
 6,
 5,
 6,
 1,
 1,
 6,
 6,
 5,
 5,
 5,
 6,
 4,
 6,
 6,
 4,
 5,
 1,
 3,
 6,
 6,
 6,
 6,
 2,
 5,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 3,
 2,
 6,
 6,
 6,
 1,
 1,
 1,
 0,
 2,
 6,
 2,
 6,
 3,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 4,
 5,
 6,
 6,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 4,
 6,
 5,
 6,
 5,
 5,
 6,
 5,
 5,
 1,
 7,
 5,
 4,
 5,
 6,
 7,
 5,
 2,
 2,
 3,
 2,
 6,
 2,
 5,
 6,
 5,
 0,
 5,
 5,
 5,
 4,
 5,
 6,
 3,
 5,
 5,
 5,
 3,
 5,
 7,
 6,
 5,
 5,
 6,
 5,
 4,
 4,
 5,
 7,
 1,
 5,
 2,
 1,
 1,
 1,
 1,
 3,
 1,
 6,
 0,
 7,
 5,
 6,
 4,
 2,
 4,
 5,
 5,
 7,
 5,
 6,
 5,
 6,
 6,
 6,
 1,
 1,
 6,
 6,
 5,
 6,
 6,
 6,
 7,
 2,
 2,
 2,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 1,
 6,
 5,
 4,
 6,
 5,
 3,
 7,
 6,
 5,
 7,
 1,
 5,
 6,
 6,
 5,
 5,
 5,
 6,
 5,
 5,
 6,
 5,
 5,
 5,
 6,
 4,
 6,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 6,
 7,
 1,
 1,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 2,
 4,
 1,
 1,
 6,
 5,
 3,
 3,
 3,
 3,
 3,
 5,
 6,
 5,
 6,
 4,
 5,
 5,
 5,
 2,
 5,
 6,
 1,
 1,
 1,
 1,
 5,
 5,
 5,
 4,
 2,
 0,
 0,
 5,
 5,
 5,
 1,
 1,
 5,
 6,
 6,
 6,
 5,
 5,
 1,
 2,
 5,
 5,
 3,
 5,
 5,
 4,
 1,
 5,
 4,
 6,
 6,
 4,
 1,
 7,
 1,
 1,
 1,
 1,
 5,
 6,
 6,
 6,
 3,
 5,
 6,
 4,
 5,
 6,
 6,
 5,
 5,
 4,
 4,
 5,
 7,
 5,
 5,
 1,
 1,
 5,
 6,
 4,
 5,
 5,
 5,
 4,
 6,
 6,
 4,
 5,
 1,
 2,
 6,
 6,
 7,
 1,
 5,
 4,
 3,
 4,
 7,
 5,
 5,
 4,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 6,
 2,
 3,
 3,
 6,
 1,
 0,
 5,
 5,
 6,
 6,
 4,
 4,
 4,
 7,
 5,
 5,
 2,
 6,
 6,
 6,
 3,
 1,
 1,
 6,
 5,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 6,
 5,
 5,
 5,
 4,
 3,
 5,
 5,
 6,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 6,
 6,
 5,
 6,
 5,
 1,
 1,
 1,
 5,
 4,
 6,
 3,
 3,
 5,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 4,
 5,
 6,
 5,
 6,
 6,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 3,
 3,
 5,
 6,
 4,
 6,
 6,
 3,
 6,
 4,
 5,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 2,
 5,
 4,
 5,
 5,
 2,
 2,
 2,
 6,
 5,
 5,
 6,
 1,
 6,
 6,
 6,
 6,
 6,
 5,
 2,
 2,
 6,
 5,
 6,
 5,
 5,
 3,
 5,
 6,
 4,
 5,
 5,
 4,
 1,
 5,
 5,
 2,
 2,
 2,
 2,
 2,
 5,
 4,
 6,
 2,
 5,
 5,
 5,
 6,
 4,
 4,
 6,
 5,
 6,
 5,
 6,
 6,
 2,
 5,
 4,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 3,
 3,
 4,
 1,
 5,
 4,
 5,
 4,
 7,
 2,
 6,
 5,
 5,
 3,
 3,
 5,
 6,
 6,
 5,
 6,
 0,
 0,
 7,
 4,
 5,
 5,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 4,
 4,
 5,
 6,
 5,
 5,
 4,
 7,
 5,
 5,
 5,
 2,
 5,
 2,
 2,
 2,
 6,
 6,
 5,
 0,
 0,
 7,
 3,
 1,
 1,
 1,
 3,
 2,
 6,
 6,
 5,
 5,
 6,
 1,
 1,
 1,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 4,
 4,
 4,
 5,
 5,
 0,
 5,
 6,
 5,
 2,
 5,
 6,
 6,
 5,
 0,
 0,
 0,
 6,
 6,
 6,
 5,
 5,
 5,
 3,
 5,
 5,
 0,
 5,
 2,
 5,
 6,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 6,
 1,
 6,
 5,
 6,
 5,
 6,
 7,
 5,
 6,
 7,
 5,
 5,
 5,
 5,
 7,
 5,
 6,
 5,
 1,
 6,
 1,
 6,
 5,
 5,
 1,
 1,
 4,
 5,
 0,
 6,
 4,
 6,
 6,
 6,
 1,
 1,
 5,
 6,
 5,
 6,
 0,
 5,
 5,
 6,
 5,
 2,
 3,
 7,
 3,
 6,
 6,
 6,
 2,
 2,
 5,
 6,
 6,
 5,
 6,
 5,
 5,
 6,
 2,
 3,
 5,
 1,
 1,
 6,
 5,
 5,
 1,
 4,
 6,
 4,
 5,
 6,
 1,
 1,
 2,
 1,
 4,
 5,
 5,
 5,
 1,
 1,
 6,
 6,
 5,
 6,
 5,
 7,
 2,
 2,
 5,
 5,
 4,
 6,
 6,
 6,
 5,
 5,
 6,
 6,
 5,
 6,
 6,
 6,
 5,
 5,
 6,
 4,
 5,
 4,
 6,
 1,
 1,
 5,
 5,
 4,
 5,
 6,
 6,
 4,
 4,
 6,
 5,
 1,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 5,
 6,
 6,
 6,
 4,
 5,
 6,
 4,
 6,
 5,
 6,
 3,
 3,
 3,
 7,
 3,
 3,
 5,
 6,
 5,
 2,
 5,
 2,
 3,
 6,
 5,
 5,
 5,
 0,
 6,
 4,
 4,
 7,
 2,
 2,
 7,
 6,
 6,
 6,
 5,
 5,
 5,
 6,
 5,
 5,
 7,
 5,
 6,
 6,
 6,
 5,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 7,
 5,
 2,
 2,
 5,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 2,
 5,
 6,
 5,
 1,
 ...]

In [122]:
side = []
for i in range(len(Cab)):
    if str(Cab[i])[-1] == 'P':
        side.append(1)
    else:
        side.append(0)
side

[1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 ...]

In [123]:
sleep_place = pd.DataFrame(train_data['CryoSleep']).values.ravel()
sleep_place_correct = []
for i in range(len(sleep_place)):
    if str((sleep_place[i]))=='True':
        sleep_place_correct.append(1)
    elif str(sleep_place[i])=='False':
        sleep_place_correct.append(-1)
    else:
        sleep_place_correct.append(0)
sleep_place_correct

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 0,
 1,
 -1,
 -1,
 1,
 1,
 0,
 -1,
 1,
 -1,
 -1,
 -1,
 0,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 0,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 0,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 0,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 0,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 0,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 0,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 0,
 0,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 0,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 0,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 0,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 ...]

In [124]:
#X_new =
print(type(sleep_place_correct))
print(type(side))
print(type(sectors))

<class 'list'>
<class 'list'>
<class 'list'>

In [132]:
X_new = [sleep_place_correct, side, sectors]
columns_new = ['sleep_place_correct', 'side', 'sectors']
X_new = pd.DataFrame(X_new).T
X_new =  X_new.rename(columns={0 : 'sleep_place_correct', 1 : 'side', 2 : 'sectors'})

In [133]:
y =  y.rename(columns = {0 : 'Transported'})

In [134]:
y

      Transported
0               0
1               1
2               0
3               0
4               1
...           ...
8688            0
8689            0
8690            1
8691            0
8692            1

[8693 rows x 1 columns]

In [135]:
X_new

      sleep_place_correct  side  sectors
0                      -1     1        1
1                      -1     0        5
2                      -1     0        0
3                      -1     0        0
4                      -1     0        5
...                   ...   ...      ...
8688                   -1     1        0
8689                    1     0        6
8690                   -1     0        6
8691                   -1     0        4
8692                   -1     0        4

[8693 rows x 3 columns]

In [136]:
from sklearn.linear_model import LogisticRegression

In [138]:
reg = LogisticRegression(random_state=2019, solver='lbfgs').fit(X_new, y.values.ravel())

In [139]:
reg.predict_proba([[-1, 0, 5]])

array([[0.65266966, 0.34733034]])

In [141]:
test_data = pd.read_csv('test_tit.csv')

In [155]:
X_test = pd.DataFrame(test_data.drop(['PassengerId', 'Name' , 'VRDeck', 'Spa' , 'ShoppingMall' , 'FoodCourt', 'RoomService','VIP' , 'Age' , 'Destination' , 'HomePlanet'], axis=1))
X_test

     CryoSleep     Cabin
0         True     G/3/S
1        False     F/4/S
2         True     C/0/S
3        False     C/1/S
4        False     F/5/S
...        ...       ...
4272      True  G/1496/S
4273     False       NaN
4274      True   D/296/P
4275     False   D/297/P
4276      True  G/1498/S

[4277 rows x 2 columns]

In [168]:
sleep_test = pd.DataFrame(test_data['CryoSleep']).values.ravel()
sleep_test_correct = []
for i in range(len(sleep_test)):
    if str((sleep_test[i]))=='True':
        sleep_test_correct.append(1)
    elif str(sleep_test[i])=='False':
        sleep_test_correct.append(-1)
    else:
        sleep_test_correct.append(0)
len(sleep_test_correct)

4277

In [157]:
Cab_test = X_test['Cabin']
sectors_test = []
for i in range(len(Cab_test)):
    if ord(str(Cab_test[i])[0]) == 110:
        sectors_test.append(78-65-6)
    else:
        sectors_test.append(ord(str(Cab_test[i])[0])-65)
len(sectors_test)

4277

In [158]:
side_test = []
for i in range(len(Cab_test)):
    if str(Cab_test[i])[-1] == 'P':
        side_test.append(1)
    else:
        side_test.append(0)
len(side_test)

4277

In [172]:
'''sleep_test_correct
sectors_test
side_test
'''
X_new_test = [sleep_test_correct, side_test, sectors_test]
X_new_test = pd.DataFrame(X_new_test).T
X_new_test =  X_new_test.rename(columns={0 : 'sleep_test_correct', 1 : 'side_test', 2 : 'sectors_test'})

In [173]:
X_new_test

      sleep_test_correct  side_test  sectors_test
0                      1          0             6
1                     -1          0             5
2                      1          0             2
3                     -1          0             2
4                     -1          0             5
...                  ...        ...           ...
4272                   1          0             6
4273                  -1          0             7
4274                   1          1             3
4275                  -1          1             3
4276                   1          0             6

[4277 rows x 3 columns]

In [185]:
Transformd_test_predict = reg.predict(X_new_test)
Transformd_test_predict_bool = []
for i in range(len(Transformd_test_predict)):
    if (Transformd_test_predict[i]) == 1:
        Transformd_test_predict_bool.append(True)
    else:
        Transformd_test_predict_bool.append(False)

In [187]:
len(Transformd_test_predict_bool)

4277

In [188]:
test_id = pd.DataFrame(test_data['PassengerId']).values.ravel()

In [192]:
predict_data = [test_id, Transformd_test_predict_bool]

In [206]:
our_prognose = pd.DataFrame(predict_data).T

In [208]:
our_prognose = our_prognose.rename(columns = {0 : 'PassengerId' ,1 : 'Transported'}, )
our_prognose

     PassengerId Transported
0        0013_01        True
1        0018_01       False
2        0019_01        True
3        0021_01       False
4        0023_01       False
...          ...         ...
4272     9266_02        True
4273     9269_01       False
4274     9271_01        True
4275     9273_01       False
4276     9277_01        True

[4277 rows x 2 columns]

In [209]:
our_prognose.to_csv('prognose.csv' , index = False)